export const GET_GAMES = 'GET_GAMES'
export const SEARCH_GAMES = 'SEARCH_GAMES'
export const ORDER = 'ORDER'
export const FILTER = 'FILTER'
export const PAGES = 'PAGES'
export const OPCION = 'OPCION'
export const LOADING = 'LOADING'
